version: '3.8'

services:
  product-db:
    image: postgres:16-alpine
    container_name: product-db
    environment:
      POSTGRES_USER: ${PRODUCT_DB_USERNAME}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}
      POSTGRES_DB: ${PRODUCT_DB_NAME}
    volumes:
      - product_db_data:/var/lib/postgresql/data
    ports:
      - "${PRODUCT_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PRODUCT_DB_USERNAME} -d ${PRODUCT_DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - supplementhub-network

  product-backend:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    container_name: product-backend
    restart: always
    depends_on:
      product-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/${PRODUCT_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${PRODUCT_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PRODUCT_DB_PASSWORD}
    ports:
      - "${PRODUCT_APP_PORT}:8080"
    networks:
      - supplementhub-network

  order-db:
    image: postgres:16-alpine
    container_name: order-db
    environment:
      POSTGRES_USER: ${ORDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB_NAME}
    volumes:
      - order_db_data:/var/lib/postgresql/data
    ports:
      - "${ORDER_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ORDER_DB_USERNAME} -d ${ORDER_DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - supplementhub-network

  order-backend:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: order-backend
    restart: always
    depends_on:
      order-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/${ORDER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${ORDER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_DB_PASSWORD}
      INVENTORY_SERVICE_URL: http://inventory-backend:8080
    ports:
      - "${ORDER_APP_PORT}:8080"
    networks:
      - supplementhub-network

  inventory-db:
    image: postgres:16-alpine
    container_name: inventory-db
    environment:
      POSTGRES_USER: ${INVENTORY_DB_USERNAME}
      POSTGRES_PASSWORD: ${INVENTORY_DB_PASSWORD}
      POSTGRES_DB: ${INVENTORY_DB_NAME}
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
    ports:
      - "${INVENTORY_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${INVENTORY_DB_USERNAME} -d ${INVENTORY_DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - supplementhub-network

  inventory-backend:
    build:
      context: ./services/inventory-service
      dockerfile: Dockerfile
    container_name: inventory-backend
    restart: always
    depends_on:
      inventory-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/${INVENTORY_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${INVENTORY_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${INVENTORY_DB_PASSWORD}
    ports:
      - "${INVENTORY_APP_PORT}:8080"
    networks:
      - supplementhub-network

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "${GATEWAY_APP_PORT}:9000"
    depends_on:
      - product-backend
      - order-backend
      - inventory-backend
    networks:
      - supplementhub-network

  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USERNAME} -d ${KEYCLOAK_DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - supplementhub-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8181
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOAK_APP_PORT}:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - supplementhub-network

volumes:
  product_db_data: {}
  order_db_data: {}
  inventory_db_data: {}
  keycloak_db_data: {}

networks:
  supplementhub-network:
    external: true
    name: supplementhub-network