version: '3.8'

services:
  product-db:
    image: postgres:16-alpine
    container_name: product-db
    environment:
      POSTGRES_USER: ${PRODUCT_DB_USERNAME}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}
      POSTGRES_DB: ${PRODUCT_DB_NAME}
    volumes:
      - product_db_data:/var/lib/postgresql/data
    ports:
      - "${PRODUCT_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PRODUCT_DB_USERNAME} -d ${PRODUCT_DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - supplementhub-network

  product-backend:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    container_name: product-backend
    restart: always
    depends_on:
      product-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/${PRODUCT_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${PRODUCT_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PRODUCT_DB_PASSWORD}
      LOKI_URL: http://loki:3100/loki/api/v1/push
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411/api/v2/spans
    ports:
      - "${PRODUCT_APP_PORT}:8080"
    networks:
      - supplementhub-network

  order-db:
    image: postgres:16-alpine
    container_name: order-db
    environment:
      POSTGRES_USER: ${ORDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB_NAME}
    volumes:
      - order_db_data:/var/lib/postgresql/data
    ports:
      - "${ORDER_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ORDER_DB_USERNAME} -d ${ORDER_DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - supplementhub-network

  order-backend:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: order-backend
    restart: always
    depends_on:
      order-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/${ORDER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${ORDER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_DB_PASSWORD}
      INVENTORY_SERVICE_URL: ${INVENTORY_SERVICE_URL}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      LOKI_URL: http://loki:3100/loki/api/v1/push
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411/api/v2/spans
    ports:
      - "${ORDER_APP_PORT}:8080"
    networks:
      - supplementhub-network

  inventory-db:
    image: postgres:16-alpine
    container_name: inventory-db
    environment:
      POSTGRES_USER: ${INVENTORY_DB_USERNAME}
      POSTGRES_PASSWORD: ${INVENTORY_DB_PASSWORD}
      POSTGRES_DB: ${INVENTORY_DB_NAME}
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
    ports:
      - "${INVENTORY_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${INVENTORY_DB_USERNAME} -d ${INVENTORY_DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - supplementhub-network

  inventory-backend:
    build:
      context: ./services/inventory-service
      dockerfile: Dockerfile
    container_name: inventory-backend
    restart: always
    depends_on:
      inventory-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/${INVENTORY_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${INVENTORY_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${INVENTORY_DB_PASSWORD}
      LOKI_URL: http://loki:3100/loki/api/v1/push
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411/api/v2/spans
    ports:
      - "${INVENTORY_APP_PORT}:8080"
    networks:
      - supplementhub-network

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "${GATEWAY_APP_PORT}:9000"
    depends_on:
      - product-backend
      - order-backend
      - inventory-backend
    environment:
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL}
      ORDER_SERVICE_URL: ${ORDER_SERVICE_URL}
      INVENTORY_SERVICE_URL: ${INVENTORY_SERVICE_URL}
      LOKI_URL: http://loki:3100/loki/api/v1/push
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411/api/v2/spans
    networks:
      - supplementhub-network

  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USERNAME} -d ${KEYCLOAK_DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - supplementhub-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}

      KC_HOSTNAME_PORT: ${KEYCLOAK_APP_PORT}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOAK_APP_PORT}:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - supplementhub-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - supplementhub-network

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    ports:
      - "${KAFKA_BROKER_PORT}:9092"
      - "${KAFKA_BROKER_INTERNAL_PORT}:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - supplementhub-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_NAME: "local"
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: "broker:29092"
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - supplementhub-network

  notification-backend:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: notification-backend
    restart: always
    depends_on:
      - broker
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      LOKI_URL: http://loki:3100/loki/api/v1/push
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://tempo:9411/api/v2/spans
    networks:
      - supplementhub-network

  loki:
    image: grafana/loki:main
    container_name: loki
    ports:
      - "${LOKI_PORT}:3100"
    command: ["-config.file=/etc/loki/local-config.yaml"]
    networks:
      - supplementhub-network

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - supplementhub-network

  tempo:
    image: grafana/tempo:2.2.2
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "${TEMPO_PORT}:3200"
      - "${ZIPKIN_PORT}:9411"
    networks:
      - supplementhub-network

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    volumes:
      - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "${GRAFANA_PORT}:3000"
    networks:
      - supplementhub-network

volumes:
  product_db_data: {}
  order_db_data: {}
  inventory_db_data: {}
  keycloak_db_data: {}

networks:
  supplementhub-network:
    external: true
    name: supplementhub-network