apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/destheboss/supplementhub-notification-service:17a9887c2f9120f0522107bbbf93da82ec2519c4
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "broker:29092"

            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_HOST
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_PORT
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_PASSWORD

            - name: LOKI_URL
              value: "http://loki:3100/loki/api/v1/push"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://tempo:9411/api/v2/spans"
