apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
  MAIL_HOST: "sandbox.smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "7c491830e8d61d"
  MAIL_PASSWORD: "ee84793d182e2e"
