apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  labels:
    app: inventory-db
spec:
  selector:
    app: inventory-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
